### PR TITLE
WIP: Added Extremas

### PR DESCRIPTION
**Pull request by mauro3**
Let me know how this looks. I still need to add docs.

### CODE REVIEW

**Comment by mauro3** [comment]
Also, would it make sense to overload `Base.minimum(::Extrema(s))` and `maximum`?

**Comment by joshday** [comment]
Awesome, thanks for doing this!  Looks good to me.  I can take care of docs.  Do you mind resubmitting the PR against the dev branch?

**Comment by mauro3** [comment]
Can I also add the minimum & maximum methods?

**Comment by joshday** [comment]
Yes, that's also a good call

**Pull request closed without merging**
