### PR TITLE
Added Extremas

### PR DESCRIPTION
**Pull request by mauro3**
Now with minimum/maximum (x-ref #68)

### CODE REVIEW

**Comment by joshday** [comment]
About to board a plane...I'll get this merged in a few hours.  Thanks again!

**Comment by mauro3** [comment]
No hurry, thanks for writing the docs and have a good flight.

**Comment by mauro3** [comment]
Actually, if you can get this merged, it would help with my `Pkg.update()`.

**Comment by joshday** [comment]
I'm in Shanghai with very spotty internet...hopefully this goes through.

**Comment by mauro3** [comment]
It did, thanks!

**Pull request merged**
