### PR TITLE
Pull request/ac3eacae

### PR DESCRIPTION
**Pull request by slundberg**
Allows weighted samples for vector, scalar, and bootstrap inputs. Just created this PR for reference. Feel free to close.

### CODE REVIEW

**Comment by slundberg** [comment]
Related to #18

**Comment by slundberg** [comment]
While working with the bootstrap methods I found out they don't support vector inputs. Since I needed that, I added support for them, and tacked it on to the end of this PR.

If you like the changes then I can peel them apart from the sampling weighting and submit a separate PR.

**Comment by joshday** [comment]
A separate PR against the dev branch would be ideal.  Otherwise, I'll be able to make the changes myself in the next day or two.

**Comment by slundberg** [comment]
Sure will do.

**Pull request closed without merging**
