### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by tbreloff**
I know I said I wouldn't do pull requests yet, but this seemed like the right time for one.  There's a ton of changes, but they mostly fall into these categories:

- overhaul of log.jl (really I just copied/pasted from my other repo where I did a little redesign)
- added/fixed some tests

lots of cleanup... here's the rules:
- anything deprecated on 0.4 I tried to fix while keeping 0.3 compatibility 
- anywhere there was a call to print/println/show I tried to use DEBUG/LOG instead.  I added a set/reset of the log_severity in the runtests.jl file so that those messages are normally quieted. Call `log_severity!(DebugSeverity)` anytime to see all log messages.
- use abstract types in method signatures where possible. (there may be places we want to force a copy to a dense array... if you see someplace where that's appropriate just add an `# OPTIMIZE: ` comment and we should tackle it properly)
- keep Vec/Mat and other concrete types as type fields and parameters, or parameterize.  i.e. do `type XX{T<:Integer}; x::T; end` if `x` can be any integer.  `update!(o, x::Integer) = ...` is ok.  `update!{T<:Real}(o, x::AVec{T}) = ...` is ok while `update!(o, x::AVec{Real}) = ...` is __not__ ok.
- try to qualify the module when overriding/extending a method: i.e. `StatsBase.coef(o) = ...`
- use rows/cols/row/col/ncols/nrows for readability
- if there's a generic version of a function, don't redefine it.  i.e. use: `update!{T}(o::OnlineStat, x::AVec{T}) = (for xi in x; update!(o, xi); end)`
- use hcat/vcat instead of bracket notation.  the bracket syntax changed from 0.3->0.4.  It'll probably change again 0.4->0.5... hcat/vcat should be more stable.

Running `Pkg.test("OnlineStats")` should give you pretty clean output now.  I even submitted a pull request to FactCheck.jl today to improve the message on test failures.

Let me know your thoughts!

### CODE REVIEW

**Comment by tbreloff** [comment]
I'm trying to get the travis tests to pass, hence the extra commits.

**Comment by joshday** [comment]
This is awesome.  Thanks for doing all this!  I merged cleanup (including changes from the additional commits) into josh and pushed.

**Comment by tbreloff** [comment]
I'm a little confused.  How exactly did you merge?  I see totally divergent commit paths after a `git fetch`

**Comment by joshday** [comment]
The same way I would've merged from the tom branch.  

```
git fetch
git merge cleanup
<make fixes>
git commit
git push
```

I started using GitHub's instructions for adding commits to the cleanup branch and then decided against it, so hopefully I didn't screw anything up.

**Comment by tbreloff** [comment]
Stop coding for a bit.  Let me clean up the commit history

**Comment by joshday** [comment]
I stopped...just trying to remove errors in the Travis build.

**Comment by tbreloff** [comment]
Ok I just pushed up branches `tom` and `master`.  Both are pointing to the same commit, which includes your recent change to opca_test.jl.  The best way to start fresh will be to fast-forward to master.  You should be able to run the following commands:
```
git fetch
git checkout josh
git merge --ff-only origin/master
```
If that worked properly, the `josh` branch will be pointing to the same commit as `tom` and `master`.  If so, you can `git push origin josh`.  I deleted the cleanup branch.

Note the `--ff-only` command is really useful.  It basically lets you "catch up" to a commit that's ahead of you, but doesn't do anything if that's not possible without a merge.  It's a safety thing so you don't accidentally start creating messy commits with auto-merges when you didn't want that.

Let me know if you have any problems/questions.

**Comment by joshday** [comment]
Cool, I'm pointing to the same commit now.  Should I have started with `git merge -ff-only origin/cleanup` and then dealt with conflicts separately?  Or was the issue that I put the merging stuff into several commits?

**Comment by tbreloff** [comment]
I'll be honest.. I'm not quite sure what you did, but you somehow picked up
changes without seemingly doing a proper merge.  The "--ff-only" only works
if you can go forward in commits.  If there's divergence, it'll require a
merge.

**Comment by joshday** [comment]
Okay, thanks.  I'll avoid whatever I did in the future.

**Pull request closed without merging**
